spring.application.name=Modern_Fashion_E-commerce_Platform

spring.datasource.url = jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username = root
spring.datasource.password = admin
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

logging.file.name = logs/ecommerce-app.log
logging.logback.rollingpolicy.max-file-size = 10MB
logging.logback.rollingpolicy.max-history = 30
logging.level.root = INFO
logging.level.com.dinh_trung_hieu.modern_fashion_ecommerce_platform = DEBUG

spring.jackson.property-naming-strategy=SNAKE_CASE