spring.application.name = Modern_Fashion_E-commerce_Platform

spring.config.import=optional:file:.env[.properties]

spring.datasource.url = ${DB_URL}
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view = false

logging.file.name = logs/ecommerce-app.log
logging.logback.rollingpolicy.max-file-size = 10MB
logging.logback.rollingpolicy.max-history = 30
logging.level.root = INFO
logging.level.com.dinh_trung_hieu.modern_fashion_ecommerce_platform = DEBUG

spring.jackson.property-naming-strategy = SNAKE_CASE

spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = ${MAIL_USERNAME}
spring.mail.password = ${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

cloudinary.cloud-name = ${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key = ${CLOUDINARY_API_KEY}
cloudinary.api-secret = ${CLOUDINARY_API_SECRET}
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Phi van chuyen mac dinh
app.order.default-shipping-fee=30000